version: "3.9"
services:

  plan1605:
    image: plan1605:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: plan1605
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/plan1605_db
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      PLANNER_SECURITY_JWT_SECRET: ${JWT_SECRET}
      PLANNER_SECURITY_ADMINS_TESTMAN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    container_name: plan1605_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: plan1605_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local